import React from 'react';
import { Info } from 'lucide-react';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import TreatmentTabs from '../components/features/TreatmentTabs';

const treatmentCards = [
  {
    title: 'Acute Pharmacotherapy',
    severity: 'Moderate',
    description:
      'First-line treatment often involves NSAIDs for mild attacks. For moderate to severe migraine, triptans are considered the standard of care.',
    action: 'View Clinical Guidelines',
  },
  {
    title: 'Preventive Medication',
    severity: 'Severe / Chronic',
    description:
      'Indicated for patients with frequent attacks (>4/month). Options include beta-blockers, anti-epileptics, and CGRP monoclonal antibodies.',
    action: 'View Efficacy Studies',
  },
  {
    title: 'Procedural Interventions',
    severity: 'Severe',
    description:
      'Interventions such as botulinum toxin injections and nerve blocks provide temporary relief for chronic migraine presentations.',
    action: 'View Procedure Details',
  },
  {
    title: 'Behavioral Therapy',
    severity: 'Mild / Adjunct',
    description:
      'CBT and biofeedback are often prescribed alongside medication to help manage pain perception and reduce triggers.',
    action: 'View Therapy Protocols',
  },
];

const TreatmentLandscapePage: React.FC = () => (
  <div className="space-y-6">
    <Card className="flex items-start gap-4 border border-amber-100 bg-amber-50">
      <Info className="text-amber-500" />
      <div className="flex-1 text-sm text-amber-700">
        <p className="font-semibold">For Informational Use Only</p>
        <p>
          This overview is generated by AI to assist in exploration. It is not a medical prescription or
          diagnosis. Always consult a qualified healthcare provider.
        </p>
      </div>
      <Button variant="outline">Dismiss</Button>
    </Card>
    <div>
      <h1 className="text-2xl font-semibold text-slate-900">Treatment Landscape: Migraine</h1>
      <p className="text-sm text-slate-500">
        A comparative overview of potential treatment pathways. Treatments for migraine typically involve a
        combination of acute relief, preventive strategies, and lifestyle adjustments.
      </p>
    </div>
    <TreatmentTabs />
    <div className="flex items-center justify-between text-xs text-slate-400">
      <span className="rounded-full bg-cyan-50 px-3 py-1 text-cyan-600">
        Active View: Modern Medicine (Allopathic)
      </span>
      <span>Severity Indicators: Mild • Moderate • Severe</span>
    </div>
    <div className="grid gap-6 md:grid-cols-2">
      {treatmentCards.map((card) => (
        <Card key={card.title} className="space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-base font-semibold text-slate-900">{card.title}</h3>
            <span className="rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-700">{card.severity}</span>
          </div>
          <p className="text-sm text-slate-500">{card.description}</p>
          <button className="text-sm font-semibold text-cyan-600">{card.action}</button>
        </Card>
      ))}
    </div>
    <div className="border-t border-slate-100 pt-10 text-center">
      <h3 className="text-lg font-semibold text-slate-900">Explore Specialist Options</h3>
      <p className="text-sm text-slate-500">
        Would you like to find a specialist who focuses on integrative approaches for Migraine?
      </p>
      <Button className="mt-4">Find a Specialist</Button>
    </div>
  </div>
);

export default TreatmentLandscapePage;
